databases:
  - name: salon-db
    plan: free
    databaseName: salon
    user: salon_user

services:
  - type: web
    name: salon-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn salon_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: salon-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://salonstore.vercel.app"
      - key: EMAIL_HOST_USER
        value: "" # Please fill this in Render Dashboard
      - key: EMAIL_HOST_PASSWORD
        value: "" # Please fill this in Render Dashboard
