# Generated by Django 5.2.15 on 2026-07-03 02:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0002_customerprofile_wallet_balance'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phản hồi',
            new_name='Feedback',
        ),
    ]
